# Import installed libraries
import pandas as pd

# Import custom modules
from source import colaborativefilter
from incomplete_search import keyword_search

path_to_books = r'/Users/abhidgd/Downloads/'
file_name = 'Books.csv'

rows = 100
columns = 5

if __name__ == '__main__':
    df_raw = pd.read_csv(path_to_books + file_name, low_memory=False,
                         dtype={ 
                                'ISBN': 'str',
                                'Book-Title': 'str',
                                'Book-Author': 'str',
                                'Year-Of-Publication': 'str',
                                'Publisher': 'str',
                                'Image-URL-S': 'str',
                                'Image-URL-M': 'str',
                                'Image-URL-L': 'str',
                                }
                        )    
    
    df = df_raw.copy()
    df = df.iloc[:rows,:columns]
    only_book_titles = df['Book-Title']

    from_user = input('Enter a keyword from the list of available books: ')

    input_to_recommender = keyword_search(key=from_user, 
                                          choices=only_book_titles,)

    recommendation = cf_recommender(df = , search = input_to_recommender,)

    print()
    print(f'Book you searched: {from_user}')
    print()
    print(f'Output from FuzzyWuzzy: {input_to_recommender}')
    print()
    print(f'Recommendation generated by Colaborative recommendation system: {recommendation}')
    print()